alter table categories alter column id set generated by default;
alter table suppliers alter column id set generated by default;
alter table supply_items alter column id set generated by default;
alter table products alter column id set generated by default;
alter table operators alter column id set generated by default;
alter table orders alter column id set generated by default;
