import type { Metadata } from "next";
import "./globals.css";
import { ClientProvider } from "./client-provider";
import { cn } from "@/_lib/utils";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
   subsets: ["latin"],
   variable: "--font-montserrat",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="pt-BR" className={cn("h-full", "antialiased", montserrat.variable)}>
         <body className="min-h-full flex flex-col">
            <ClientProvider>{children}</ClientProvider>
         </body>
      </html>
   );
}
